### ISSUE TITLE
Add states history.

### ISSUE THREAD

**Issue by iagodahlem** [rafaeleyng/macchina#1]
Add states history to be possible get past states. Something like:

```js
const states = [
  {name: '1'},
  {name: '2'},
]
const macchina = new Macchina(states)
macchina.transition('1')
macchina.transition('2')
macchina.transition('1')

macchina.getPreviousState() // => {name: '2'}
macchina.getHistoryState() // => [{name: '1'}, {name: '2'}, {name: '1'}]
```

**Comment by rafaeleyng** [comment]
Hi @iagodahlem , sorry for the late response.

As we talked, I don't think the FSM should remember it's history. Automatas doesn't have memory.

I think you should create extra states to represent the conditions you need to test and take your actions based on the current state only.

For instance:

![image](https://cloud.githubusercontent.com/assets/4842605/21743909/00583b84-d4f3-11e6-96cf-df417b26c502.png)

If you are in state C and want to know from what state you came from to decide whether you are going to state D or E, I think you are doing it wrong.

What you should to is to create a new state N, that could have the same properties that C if you like, and use N as a way to remember that "you came from state B, so you should go to state E":

![screen shot 2017-01-07 at 4 06 56 pm](https://cloud.githubusercontent.com/assets/4842605/21743934/5fc834de-d4f3-11e6-980b-a187a4d0f393.png)
